title: Paul Kenny
tagline: "A software developer's blog and portfolio"
description: "PK's blog and portfolio" 
author: Paul Kenny
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pskenny.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  pskenny
repository: pskenny/pskenny.github.io

header_pages:
  - blog.md
  - ideas.md

minima:
  skin: dark

# Build settings
theme: minima
plugins:
  - jekyll-feed

