title: Paul Kenny
description: "I'm a Software Development graduate." 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pskenny.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pskenny
repository: pskenny/pskenny.github.io

header_pages:
  - blog.md
  - ideas.md

minima:
  skin: dark

# Build settings
theme: minima
plugins:
  - jekyll-feed

