title: Paul Kenny
description: "PK's blog and portfolio"
author: Paul Kenny
baseurl: ""
url: "https://pskenny.github.io"
locale: "en"

github_username: pskenny
repository: pskenny/pskenny.github.io

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: "_pages/ideas.md"
      type: pages
    values:
      permalink: "ideas"
      layout: single
  - scope:
      path: "_pages/blog.md"
      type: pages
    values:
      permalink: "blog"
      layout: single
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      share: true
      related: true

remote_theme: "mmistakes/minimal-mistakes@4.21.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
